### PR TITLE
Change experimental tag to beta tag

### PR DESCRIPTION
**Pull request by loosebazooka**

### CODE REVIEW

**Comment by loosebazooka** [comment]
@meltsufin @patflynn @lesv

**Comment by patflynn** [comment]
LGTM. Apart from the failing build of course.

**Comment by lesv** [comment]
LGTM - Thanks, should probably fix your build as well.   I think Pat also asked bumping the version to 1.0-BETA

**Comment by meltsufin** [comment]
:ship:

**Pull request closed without merging**
