### PR TITLE
Fix bullet

### PR DESCRIPTION
**Pull request by shiraji**

### CODE REVIEW

**Comment by TadCordle** [comment]
I believe these were intended to be footnotes, not bullets.

**Comment by shiraji** [comment]
OK

**Comment by shiraji** [comment]
image

but this seems really hard read as a footnote...

**Comment by suztomo** [comment]
Thank you for feedback. I also see the footnote (2nd one) is broken.

Changing
“property. * setting”  -> “property, while setting”
will make them look better

**Comment by suztomo** [comment]
Fixed in #331.

**Pull request closed without merging**
