### PR TITLE
Add java8 workaround for devAppServer

### PR DESCRIPTION
**Pull request by loosebazooka**

### CODE REVIEW

**Comment by loosebazooka** [comment]
@meltsufin perhaps moving this into common library is the way to go?

**Comment by meltsufin** [comment]
In the maven plugin, we only pass this flag if we detect Java 8.

**Comment by loosebazooka** [comment]
makes sense, let me adjust

**Comment by loosebazooka** [comment]
@meltsufin ptal

**Comment by meltsufin** [comment]
:boat:

**Pull request merged**
