### PR TITLE
Link to relevant configuration sections

### PR DESCRIPTION
**Pull request by TWiStErRob**

### CODE REVIEW

**Review by zhumin8 — APPROVED** [review]
Thanks for adding the link!
We'll merge in once the ci test passes.

**Comment by emmileaf** [comment]
The failing check here is from a configuration update in the CI environment - could you rebase this off the latest fix in the main branch? Thanks!

**Comment by TWiStErRob** [comment]
There should be a rebase button on the PR...

**Comment by TWiStErRob** [comment]
Done, but please enable rebase updates on PRs... it "only" replaces this task:

```shell
> git clone https://github.com/GoogleCloudPlatform/app-gradle-plugin

> git branch -a
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/patch-1

> git remote add up https://github.com/GoogleCloudPlatform/app-gradle-plugin

> git fetch up
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Total 4 (delta 3), reused 3 (delta 3), pack-reused 0
Unpacking objects: 100% (4/4), 931 bytes | 62.00 KiB/s, done.
From https://github.com/GoogleCloudPlatform/app-gradle-plugin
 * [new branch]      master                -> up/master

> git checkout patch-1
Switched to a new branch 'patch-1'
branch 'patch-1' set up to track 'origin/patch-1'.

> git rebase -i up/master
Successfully rebased and updated refs/heads/patch-1.

> git status
On branch patch-1
Your branch and 'origin/patch-1' have diverged,
and have 2 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working tree clean

> git push -f
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.

> cd ..
> rm -rf app-gradle-plugin
```

**Review by emmileaf — APPROVED** [review]
Apologies for the inconveniences here - thanks again for the contribution!

**Pull request merged**
