### PR TITLE
Fix all known javadoc issues

### PR DESCRIPTION
**Pull request by TWiStErRob**
<details><summary><code>gradlew javadoc</code></summary>

```
> Task :javadoc
src\main\java\com\google\cloud\tools\gradle\appengine\standard\AppEngineStandardExtension.java:40:
warning: no @param for project
  public void createSubExtensions(Project project) {
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\standard\DevAppServerRunTask.java:43:
warning: no @throws for com.google.cloud.tools.appengine.AppEngineException
  public void runAction() throws AppEngineException, ProjectConfigurationException {
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\standard\DevAppServerStartTask.java:64:
warning: no @throws for com.google.cloud.tools.appengine.AppEngineException
  public void startAction() throws AppEngineException, IOException {
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\standard\DevAppServerStartTask.java:64:
warning: no @throws for java.io.IOException
  public void startAction() throws AppEngineException, IOException {
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\standard\ExplodeWarTask.java:37:
warning: no @param for explodedAppDirectory
  public void setExplodedAppDirectory(File explodedAppDirectory) {
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\standard\RunExtension.java:134:
warning: no @param for serviceProject
  public File projectAsService(String serviceProject) {
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\standard\RunExtension.java:134:
warning: no @return
  public File projectAsService(String serviceProject) {
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\standard\RunExtension.java:142:
warning: no @param for serviceProject
  public File projectAsService(Project serviceProject) {
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\standard\RunExtension.java:142:
warning: no @return
  public File projectAsService(Project serviceProject) {
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\standard\StageStandardExtension.java:49:
warning: no @param for project
  public StageStandardExtension(Project project) {
         ^
src\main\java\com\google\cloud\tools\gradle\appengine\standard\StageStandardTask.java:48:
warning: no @throws for com.google.cloud.tools.appengine.AppEngineException
  public void stageAction() throws AppEngineException {
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\AppEngineCorePluginConfiguration.java:60:
warning: no @param for project
  public void configureCoreProperties(
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\AppEngineCorePluginConfiguration.java:60:
warning: no @param for appEngineCoreExtensionProperties
  public void configureCoreProperties(
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\AppEngineCorePluginConfiguration.java:60:
warning: no @param for taskGroup
  public void configureCoreProperties(
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\AppEngineCorePluginConfiguration.java:60:
warning: no @param for requiresAppEngineJava
  public void configureCoreProperties(
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\CheckCloudSdkTask.java:50:
warning: no @throws for com.google.cloud.tools.appengine.operations.cloudsdk.CloudSdkNotFoundException
  public void checkCloudSdkAction()
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\CheckCloudSdkTask.java:50:
warning: no @throws for com.google.cloud.tools.appengine.operations.cloudsdk.CloudSdkVersionFileException
  public void checkCloudSdkAction()
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\CheckCloudSdkTask.java:50:
warning: no @throws for com.google.cloud.tools.appengine.operations.cloudsdk.CloudSdkOutOfDateException
  public void checkCloudSdkAction()
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\CheckCloudSdkTask.java:50:
warning: no @throws for com.google.cloud.tools.appengine.operations.cloudsdk.AppEngineJavaComponentsNotInst
alledException
  public void checkCloudSdkAction()
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\CloudSdkLoginTask.java:34:
warning: no @throws for com.google.cloud.tools.appengine.AppEngineException
  public void login() throws AppEngineException {
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\CloudSdkOperations.java:71:
warning: no @return
  public DevServers getDevServers() {
                    ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\CloudSdkOperations.java:79:
warning: no @return
  public AppCfg getAppcfg() {
                ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\CloudSdkOperations.java:84:
warning: no @param for logger
  public static ProcessHandler getDefaultHandler(Logger logger) {
                               ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\CloudSdkOperations.java:84:
warning: no @return
  public static ProcessHandler getDefaultHandler(Logger logger) {
                               ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\DeployAllTask.java:51:
warning: no @throws for com.google.cloud.tools.appengine.AppEngineException
  public void deployAllAction() throws AppEngineException {
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\DeployCronTask.java:40:
warning: no @throws for com.google.cloud.tools.appengine.AppEngineException
  public void deployAction() throws AppEngineException {
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\DeployDispatchTask.java:41:
warning: no @throws for com.google.cloud.tools.appengine.AppEngineException
  public void deployAction() throws AppEngineException {
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\DeployDosTask.java:40:
warning: no @throws for com.google.cloud.tools.appengine.AppEngineException
  public void deployAction() throws AppEngineException {
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\DeployIndexTask.java:40:
warning: no @throws for com.google.cloud.tools.appengine.AppEngineException
  public void deployAction() throws AppEngineException {
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\DeployQueueTask.java:40:
warning: no @throws for com.google.cloud.tools.appengine.AppEngineException
  public void deployAction() throws AppEngineException {
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\DeployTargetResolver.java:61:
warning: no @param for configString
  public String getProject(String configString) {
                ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\DeployTargetResolver.java:61:
warning: no @return
  public String getProject(String configString) {
                ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\DeployTargetResolver.java:89:
warning: no @param for configString
  public String getVersion(String configString) {
                ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\DeployTargetResolver.java:89:
warning: no @return
  public String getVersion(String configString) {
                ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\DeployTask.java:48:
warning: no @throws for com.google.cloud.tools.appengine.AppEngineException
  public void deployAction() throws AppEngineException {
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\DownloadCloudSdkTask.java:62:
warning: no @throws for com.google.cloud.tools.managedcloudsdk.ManagedSdkVerificationException
  public void downloadCloudSdkAction()
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\DownloadCloudSdkTask.java:62:
warning: no @throws for com.google.cloud.tools.managedcloudsdk.ManagedSdkVersionMismatchException
  public void downloadCloudSdkAction()
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\DownloadCloudSdkTask.java:62:
warning: no @throws for java.lang.InterruptedException
  public void downloadCloudSdkAction()
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\DownloadCloudSdkTask.java:62:
warning: no @throws for com.google.cloud.tools.managedcloudsdk.command.CommandExecutionException
  public void downloadCloudSdkAction()
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\DownloadCloudSdkTask.java:62:
warning: no @throws for com.google.cloud.tools.managedcloudsdk.install.SdkInstallerException
  public void downloadCloudSdkAction()
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\DownloadCloudSdkTask.java:62:
warning: no @throws for com.google.cloud.tools.managedcloudsdk.command.CommandExitException
  public void downloadCloudSdkAction()
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\DownloadCloudSdkTask.java:62:
warning: no @throws for java.io.IOException
  public void downloadCloudSdkAction()
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\ManagedCloudSdkFactory.java:35:
warning: no @return
  public ManagedCloudSdk newManagedSdk()
                         ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\ManagedCloudSdkFactory.java:35:
warning: no @throws for com.google.cloud.tools.managedcloudsdk.UnsupportedOsException
  public ManagedCloudSdk newManagedSdk()
                         ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\ManagedCloudSdkFactory.java:35:
warning: no @throws for com.google.cloud.tools.managedcloudsdk.BadCloudSdkVersionException
  public ManagedCloudSdk newManagedSdk()
                         ^
src\main\java\com\google\cloud\tools\gradle\appengine\core\ShowConfigurationTask.java:51:
warning: no @throws for java.lang.IllegalAccessException
  public void showConfiguration() throws IllegalAccessException {
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\sourcecontext\GenRepoInfoFileExtension.java:36:
warning: no @param for project
  public GenRepoInfoFileExtension(Project project) {
         ^
src\main\java\com\google\cloud\tools\gradle\appengine\sourcecontext\GenRepoInfoFileTask.java:48:
warning: no @throws for com.google.cloud.tools.appengine.AppEngineException
  public void generateRepositoryInfoFile() throws AppEngineException {
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\appyaml\AppEngineAppYamlExtension.java:38:
warning: no @param for project
  public void createSubExtensions(Project project) {
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\appyaml\StageAppYamlExtension.java:89:
warning: no @return
  public FileCollection getExtraFilesDirectoriesAsInputFiles() {
                        ^
src\main\java\com\google\cloud\tools\gradle\appengine\appyaml\StageAppYamlTask.java:42:
warning: no @throws for com.google.cloud.tools.appengine.AppEngineException
  public void stageAction() throws AppEngineException {
              ^
src\main\java\com\google\cloud\tools\gradle\appengine\util\AppEngineWebXml.java:53:
warning: no @return
  public boolean isVm() {
                 ^
src\main\java\com\google\cloud\tools\gradle\appengine\util\ExtensionUtil.java:35:
warning: no @param for <T>
  public <T> T get(String... path) {
               ^
src\main\java\com\google\cloud\tools\gradle\appengine\util\ExtensionUtil.java:35:
warning: no @param for path
  public <T> T get(String... path) {
               ^
src\main\java\com\google\cloud\tools\gradle\appengine\util\ExtensionUtil.java:35:
warning: no @return
  public <T> T get(String... path) {
               ^
55 warnings
```
</details>

<details><summary><code>gradlew checkstyleMain</code></summary>

```
> Task :checkstyleMain
[ant:checkstyle] [WARN] src\main\java\com\google\cloud\tools\gradle\appengine\appyaml\AppEngineAppYamlExtension.java:28:1: Missing a Javadoc comment. [MissingJavadocType]
[ant:checkstyle] [WARN] src\main\java\com\google\cloud\tools\gradle\appengine\core\AppEngineCoreExtensionProperties.java:20:1: Missing a Javadoc comment. [MissingJavadocType]
[ant:checkstyle] [WARN] src\main\java\com\google\cloud\tools\gradle\appengine\core\CheckCloudSdkTask.java:30:1: Missing a Javadoc comment. [MissingJavadocType]
[ant:checkstyle] [WARN] src\main\java\com\google\cloud\tools\gradle\appengine\core\CloudSdkLoginTask.java:24:1: Missing a Javadoc comment. [MissingJavadocType]
[ant:checkstyle] [WARN] src\main\java\com\google\cloud\tools\gradle\appengine\core\DeployAllTask.java:31:1: Missing a Javadoc comment. [MissingJavadocType]
[ant:checkstyle] [WARN] src\main\java\com\google\cloud\tools\gradle\appengine\core\DownloadCloudSdkTask.java:41:1: Missing a Javadoc comment. [MissingJavadocType]
[ant:checkstyle] [WARN] src\main\java\com\google\cloud\tools\gradle\appengine\core\DownloadCloudSdkTaskConsoleListener.java:24:1: Missing a Javadoc comment. [MissingJavadocType]
[ant:checkstyle] [WARN] src\main\java\com\google\cloud\tools\gradle\appengine\core\GcloudTask.java:23:1: Missing a Javadoc comment. [MissingJavadocType]
[ant:checkstyle] [WARN] src\main\java\com\google\cloud\tools\gradle\appengine\core\ManagedCloudSdkFactory.java:26:1: Missing a Javadoc comment. [MissingJavadocType]
[ant:checkstyle] [WARN] src\main\java\com\google\cloud\tools\gradle\appengine\standard\AppEngineStandardExtension.java:28:1: Missing a Javadoc comment. [MissingJavadocType]
[ant:checkstyle] [WARN] src\main\java\com\google\cloud\tools\gradle\appengine\util\ExtensionUtil.java:23:1: Missing a Javadoc comment. [MissingJavadocType]
[ant:checkstyle] [WARN] src\main\java\com\google\cloud\tools\gradle\appengine\util\NullSafe.java:24:1: Missing a Javadoc comment. [MissingJavadocType]
```
</details>

### CODE REVIEW

**Comment by TWiStErRob** [comment]
@JoeWang1127 Should we re-raise these PRs? do you have capacity to review now? Please comment on the PRs why you're closing them.

**Comment by JoeWang1127** [comment]
Hi @TWiStErRob, we plan to archive this repo and I see this PR hasn't been touched for almost a year.

The content of this repo lives in https://github.com/GoogleCloudPlatform/appengine-plugins so fell free to open another one there.

**Comment by TWiStErRob** [comment]
> ... and I see this PR hasn't been touched for almost a year.

Yes, I opened the PR a year ago, and no maintainer did a review, nothing I can do about that :).
I don't know what to do. I'm happy to rework and reopen in the new repo, but only if there's capacity to review from Google's side, otherwise I feel like I'm throwing out hours of work. @JoeWang1127 can you please give an insight if our PRs will get traction or not in the new repo?

**Comment by suztomo** [comment]
Sorry for having not reviewing this pull request. This change of Javadoc looks good. I will review once it comes to https://github.com/GoogleCloudPlatform/appengine-plugins/.

**Pull request closed without merging**
